# Generated by Django 5.0.6 on 2024-05-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('ataque', models.IntegerField(blank=True, null=True)),
                ('defesa', models.IntegerField(blank=True, null=True)),
                ('api_id', models.IntegerField(unique=True)),
                ('imagem_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('extra_deck', models.ManyToManyField(related_name='extra_decks', to='decks.carta')),
                ('main_deck', models.ManyToManyField(related_name='main_decks', to='decks.carta')),
                ('side_deck', models.ManyToManyField(related_name='side_decks', to='decks.carta')),
            ],
        ),
    ]
