# Generated by Django 5.0.6 on 2024-06-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
