# Generated by Django 5.0.3 on 2024-05-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygo_deck_builder', '0002_deck_extra_deck_deck_main_deck_deck_side_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('atk', models.IntegerField(blank=True, null=True)),
                ('defense', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('race', models.CharField(max_length=50)),
                ('attribute', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='deck',
            name='extra_deck',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='main_deck',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='side_deck',
        ),
        migrations.AddField(
            model_name='deck',
            name='extra_deck',
            field=models.ManyToManyField(blank=True, related_name='extra_decks', to='ygo_deck_builder.card'),
        ),
        migrations.AddField(
            model_name='deck',
            name='main_deck',
            field=models.ManyToManyField(blank=True, related_name='main_decks', to='ygo_deck_builder.card'),
        ),
        migrations.AddField(
            model_name='deck',
            name='side_deck',
            field=models.ManyToManyField(blank=True, related_name='side_decks', to='ygo_deck_builder.card'),
        ),
    ]
